"""create_master_device_and_house_schema

Revision ID: ffb261857ae2
Revises: 
Create Date: 2026-09-23 18:27:37.052085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffb261857ae2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('current_mode', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('house_id', 'name', name='uq_device_group_house_name')
    )
    op.create_index(op.f('ix_device_groups_house_id'), 'device_groups', ['house_id'], unique=False)
    op.create_table('elderly_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('medical_history', sa.Text(), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elderly_profiles_house_id'), 'elderly_profiles', ['house_id'], unique=False)
    op.create_table('house_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_in_house', sa.String(length=50), nullable=False),
    sa.Column('permissions', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('house_id', 'user_id', name='uq_house_member')
    )
    op.create_index(op.f('ix_house_members_house_id'), 'house_members', ['house_id'], unique=False)
    op.create_index(op.f('ix_house_members_user_id'), 'house_members', ['user_id'], unique=False)
    op.create_table('device_configs',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('stream_url', sa.String(length=500), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=False),
    sa.Column('is_sleep', sa.Boolean(), nullable=False),
    sa.Column('is_ai_protect', sa.Boolean(), nullable=False),
    sa.Column('has_two_way_audio', sa.Boolean(), nullable=False),
    sa.Column('hr_threshold_high', sa.Integer(), nullable=False),
    sa.Column('hr_threshold_low', sa.Integer(), nullable=False),
    sa.Column('spo2_threshold_low', sa.Integer(), nullable=False),
    sa.Column('fall_impact_threshold', sa.Float(), nullable=False),
    sa.Column('immobility_seconds', sa.Integer(), nullable=False),
    sa.Column('mqtt_topic', sa.String(length=150), nullable=True),
    sa.Column('extra_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.add_column('devices', sa.Column('sub_title', sa.String(length=255), nullable=True))
    op.add_column('devices', sa.Column('device_type', sa.String(length=30), nullable=False))
    op.add_column('devices', sa.Column('status_text', sa.String(length=150), nullable=True))
    op.add_column('devices', sa.Column('battery_level', sa.SmallInteger(), nullable=True))
    op.add_column('devices', sa.Column('mac_address', sa.String(length=50), nullable=True))
    op.add_column('devices', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('devices', sa.Column('house_id', sa.UUID(), nullable=True))
    op.add_column('devices', sa.Column('group_id', sa.UUID(), nullable=True))
    op.add_column('devices', sa.Column('elderly_id', sa.UUID(), nullable=True))
    op.add_column('devices', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('devices', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.create_index(op.f('ix_devices_device_type'), 'devices', ['device_type'], unique=False)
    op.create_index(op.f('ix_devices_elderly_id'), 'devices', ['elderly_id'], unique=False)
    op.create_index(op.f('ix_devices_group_id'), 'devices', ['group_id'], unique=False)
    op.create_index(op.f('ix_devices_house_id'), 'devices', ['house_id'], unique=False)
    op.create_index(op.f('ix_devices_last_heartbeat'), 'devices', ['last_heartbeat'], unique=False)
    op.create_index(op.f('ix_devices_owner_id'), 'devices', ['owner_id'], unique=False)
    op.drop_constraint(op.f('devices_owner_id_fkey'), 'devices', type_='foreignkey')
    op.create_foreign_key('fk_devices_owner_id', 'devices', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_devices_house_id', 'devices', 'houses', ['house_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_devices_group_id', 'devices', 'device_groups', ['group_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_devices_elderly_id', 'devices', 'elderly_profiles', ['elderly_id'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint('fk_devices_elderly_id', 'devices', type_='foreignkey')
    op.drop_constraint('fk_devices_group_id', 'devices', type_='foreignkey')
    op.drop_constraint('fk_devices_house_id', 'devices', type_='foreignkey')
    op.drop_constraint('fk_devices_owner_id', 'devices', type_='foreignkey')
    op.create_foreign_key(op.f('devices_owner_id_fkey'), 'devices', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_devices_owner_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_last_heartbeat'), table_name='devices')
    op.drop_index(op.f('ix_devices_house_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_group_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_elderly_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_type'), table_name='devices')
    op.alter_column('devices', 'name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('devices', 'updated_at')
    op.drop_column('devices', 'elderly_id')
    op.drop_column('devices', 'group_id')
    op.drop_column('devices', 'house_id')
    op.drop_column('devices', 'ip_address')
    op.drop_column('devices', 'mac_address')
    op.drop_column('devices', 'battery_level')
    op.drop_column('devices', 'status_text')
    op.drop_column('devices', 'device_type')
    op.drop_column('devices', 'sub_title')
    op.drop_table('device_configs')
    op.drop_index(op.f('ix_house_members_user_id'), table_name='house_members')
    op.drop_index(op.f('ix_house_members_house_id'), table_name='house_members')
    op.drop_table('house_members')
    op.drop_index(op.f('ix_elderly_profiles_house_id'), table_name='elderly_profiles')
    op.drop_table('elderly_profiles')
    op.drop_index(op.f('ix_device_groups_house_id'), table_name='device_groups')
    op.drop_table('device_groups')
    op.drop_table('houses')
    # ### end Alembic commands ###
